spring:
  application:
    name: OnlineShop
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  sql:
    init:
      mode: never
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}
    url: jdbc:mysql://localhost:3306/perfumes_shop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080

forex:
  api:
    key: ${FOREX_API_KEY:}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"

shipping:
  api:
    baseUrl: "http://localhost:8081"

jwt:
  secret: ${JWT_KEY:LuSKCYKrjCsc1blrhRKpWNbWUP1wzNfS5a6DX4hS6MIKN3e8KYLuSKCYKrjCsc1blrhRKpWNbWUP1wzNfS5a6DX4hS6MIKN3e8KY}
  expiration: 60000